language: node_js
node_js: 12
script:
- npm run lint
after_success:
- npx semantic-release
env:
  global:
  # GH_TOKEN
  - secure: ykWb441405CcwQmKO+uLRJ4v0B0/6hwdSjPF8cYjpHaAYduhRHBCO+27I9fwRU+nvYxgxvSB4dPdEHzrZ76QaSmn8kQFFvQEaTlIVzKSx1+Jp8PXe1SB0KXHaGbDNY5Auz50DFYBMvmGYuLK4jNTD+G8uoO5Tf/VMxFuI//qQNUzzwlVetUdCOdzrIkwtmUoAcwz9KdcvgNfQYomrE12mPv5Qhc1GfbS3CO+tQp0uD48fL/IJif1rr184Zj2c0BHcFkyE63artbsnr0641VLBLbRZx00zpYGivORfOx26weXB58pzsI0Ue9X1JRo4gnMPxD1BZy/5sq0uo2uWR7ENWp8puPxpfiP4JdNMG9HFDG29mNaI6hqvMG8cUweioFrwenCbRM05B1xZlSZcZChHekWAxaQY9ScwgQ0Fhvx0iuRNga/Te1wDRLtO9cpEaDpZWX0lUOtI6KOApEUErew60kEfZDVXR55pMu4rY4wiPn6WsL1HrR/PnIb2Du7YNuHwobCSN3aHGD3HhnJqjLQSOEs0f2sWXEutKjo/oHc8tfLO2d0pMBFdYOFEB1vHWHDrQPMmPS9jp0OK89cILGaj8W4rqKpDKICQV8XFCSrC2jrMs/nx8t61gC5OEoxoi4X0rniu7oyZ5EsldLme4g72kru4kAZq++R9C7w7M7KP/g=
  # NPM_TOKEN
  - secure: tNAZupmBsjwU/Dunts765EQ2S57uXHc3/fvMFHY53Hlrv0RKAjQsM3PWI4AR2s2Obi2Kqd+G5E6OnogqKzZC2QOgRwaCsxK0nz25M4r8QyWCtvdOiGv+VbPXYeITlFagZ/kfdpeSppYwTsWIfvownJZ62Y7kiL8trFKEZ/yuWGBm02zelRPOIhhg+DRTwy3jYZqZD4dn8FqZ+idecuNM+nlN1FXsmcfT9jqPlc6WJKFrurjtsIJSdtEqy7xFPSsfRway5k7idSAnR6YnpepKMpWwFgIeh9rV6sWGl+mMG9OKpNkkYU6UEVXtZVcTijhvF9KBcvCQbI7URxzjK2lYRsymFsqIwqnNpMYRCnOcz7AkjN6KFEmBCw/cScfndic4xTn3Knwcb/J8FGv6wqizl4DRgBBJyu8C2YVNsuTYbPZFCx8D3cy+GYadODyUT3hPvgYZUKigTh/dp0mMN03E6EMxcp0unhIJyyRjIWR3BKAwmhDlFSXIUTIBs8RYDxNTPH4CoSQvx89OAIQSXdTFnW/P/lsxgCsF2eZ0/8nYGcEIcKaxf7E+zZvnrKRXVJo+UYEFRuOTLu0m2vPf/2C7I8phF4yAFicO4u6tged9bMo1mPP3wV+OCtdSetwdgdEJeRH0Qh40OV1agCFUJiB83nE5U5MBgh2LqBOggjaLH3I=
